# gruvbox material dark soft
set $bg_dim #252423
set $bg0 #23202f
set $bg1 #3c3836
set $bg2 #3c3836
set $bg3 #504945
set $bg4 #504945
set $bg5 #665c54
set $bg_diff_red #472322
set $bg_diff_green #3d4220
set $bg_diff_blue #0f3a42
set $bg_statusline1 #3c3836
set $bg_statusline2 #46413e
set $bg_statusline3 #5b534d
set $bg_current_word #45403d
set $bg_visual_red #543937
set $bg_visual_green #424a3e
set $bg_visual_blue #404946
set $bg_visual_yellow #574833
set $bg_visual_purple #4b3e45
set $fg0 #d4be98
set $fg1 #ddc7a1
set $red #ea6962
set $green #a9b665
set $blue #7daea3
set $yellow #d8a657
set $purple #d3869b
set $orange #e78a4e
set $aqua #89b482
set $bg_red #ea6962
set $bg_green #a9b665
set $bg_yellow #d8a657
set $grey0 #7c6f64
set $grey1 #928374
set $grey2 #a89984


# target                        title           bg              text            indicator       border
client.focused                  $bg_green       $bg0            $fg0            $purple         $bg_green
client.focused_inactive         $fg1            $bg1            $fg1            $purple         $fg1
client.unfocused                $bg5            $bg0            $bg5            $purple         $fg1
client.urgent                   $red            $red            $fg0            $red            $red
client.placeholder              $bg0            $bg0            $fg0            $grey1          $grey1

